def generate_config(
        electrons_per_angstrom=2,
        dimentions=(4096, 4096, 1024),
        phase_plates=False,
        phase_shift=90,
        defocus=-2.5,
        tetris='tetrises/0/atomic_angposfile.txt',
        start_angle=-60,
        step_angle=2,
        density=1,
        output_config='parakeet/0/config.yaml',
        GPU_ID='0'
):
    config = "multiprocessing:\n"
    config += "  device: {}\n".format(['cpu', 'gpu'][1])
    config += "  gpu_id:\n"
    config += "  - {}\n".format(GPU_ID)
    config += "  nproc: {}\n".format(1)

    config += "microscope:\n"
    config += "  beam:\n"
    config += "    acceleration_voltage_spread: {}\n".format(8e-07)
    config += "    electrons_per_angstrom: {}\n".format(electrons_per_angstrom)
    config += "    energy: {}\n".format(300.0)
    config += "    energy_spread: {}\n".format(2.66e-06)
    config += "    phi: {}\n".format(0.0)
    config += "    illumination_semiangle: {}\n".format(0.02)
    config += "    theta: {}\n".format(0.0)
    config += "  detector:\n"
    config += "    dqe: {}\n".format(True)
    config += "    nx: {}\n".format(dimentions[0])
    config += "    ny: {}\n".format(dimentions[1])
    config += "    origin:\n"
    config += "    - {}\n".format(0)
    config += "    - {}\n".format(0)
    config += "    pixel_size: {}\n".format(1)
    config += "  lens:\n"
    config += "    c_10: {}\n".format(defocus*10000)
    config += "    c_12: {}\n".format(0)
    config += "    c_21: {}\n".format(0)
    config += "    c_23: {}\n".format(0)
    config += "    c_30: {}\n".format(2.7)
    config += "    c_32: {}\n".format(0)
    config += "    c_34: {}\n".format(0)
    config += "    c_41: {}\n".format(0)
    config += "    c_43: {}\n".format(0)
    config += "    c_45: {}\n".format(0)
    config += "    c_50: {}\n".format(0)
    config += "    c_52: {}\n".format(0)
    config += "    c_54: {}\n".format(0)
    config += "    c_56: {}\n".format(0)
    config += "    c_c: {}\n".format(2.7)
    config += "    current_spread: {}\n".format(3.3e-07)
    config += "    phi_12: {}\n".format(0)
    config += "    phi_21: {}\n".format(0)
    config += "    phi_23: {}\n".format(0)
    config += "    phi_32: {}\n".format(0)
    config += "    phi_34: {}\n".format(0)
    config += "    phi_41: {}\n".format(0)
    config += "    phi_43: {}\n".format(0)
    config += "    phi_45: {}\n".format(0)
    config += "    phi_52: {}\n".format(0)
    config += "    phi_54: {}\n".format(0)
    config += "    phi_56: {}\n".format(0)
    config += "  model: {}\n".format(['krios', 'talos', 'null'][2])
    config += "  phase_plate:\n"
    config += "    phase_shift: {}\n".format(phase_shift)
    config += "    radius: {}\n".format(0.005)
    config += "    use: {}\n".format(phase_plates)
    config += "sample:\n"
    config += "  box:\n"
    config += "  - {}\n".format(dimentions[0])
    config += "  - {}\n".format(dimentions[1])
    config += "  - {}\n".format(dimentions[2])
    config += "  centre:\n"
    config += "  - {}\n".format(dimentions[0] // 2)
    config += "  - {}\n".format(dimentions[1] // 2)
    config += "  - {}\n".format(dimentions[2] // 2)
    config += "  coords: null\n"
    config += "  ice: null\n"
    config += "  molecules:\n"
    config += "    local:\n"
    file = open(tetris, mode='r')
    file_content = file.read()
    file.close()
    config += file_content
    config += "  shape:\n"
    config += "    cube:\n"
    config += "      length: {}\n".format(1)
    config += "    cuboid:\n"
    config += "      length_x: {}\n".format(dimentions[0])
    config += "      length_y: {}\n".format(dimentions[1])
    config += "      length_z: {}\n".format(dimentions[2])
    config += "    cylinder:\n"
    config += "      axis:\n"
    config += "      - {}\n".format(0)
    config += "      - {}\n".format(1)
    config += "      - {}\n".format(0)
    config += "      length: {}\n".format(1)
    config += "      offset_x: null\n"
    config += "      offset_z: null\n"
    config += "      radius: {}\n".format(1)
    config += "    margin:\n"
    config += "      - {}\n".format(0)
    config += "      - {}\n".format(0)
    config += "      - {}\n".format(0)
    config += "    type: {}\n".format(['cube', 'cuboid', 'cylinder'][1])
    config += "  sputter: null\n"
    config += "scan:\n"
    config += "  angles: null\n"
    config += "  axis:\n"
    config += "  - {}\n".format(0)
    config += "  - {}\n".format(1)
    config += "  - {}\n".format(0)
    config += "  drift: null\n"
    config += "  exposure_time: {}\n".format(1)

    config += "  mode: {}\n".format(
        ['still', 'single_particle', 'tilt_series', 'dose_symmetric', 'manual'][3])
    config += "  num_images: {}\n".format(len(range(start_angle, -start_angle+step_angle, step_angle)))
    config += "  num_nhelix: 1\n"
    config += "  phi: null\n"
    config += "  positions: null\n"
    config += "  start_angle: {}\n".format(start_angle)
    config += "  start_pos: 0\n"
    config += "  step_angle: {}\n".format(step_angle)
    config += "  step_pos: auto\n"
    config += "  theta: null\n"

    config += "simulation:\n"
    config += "  division_thickness: 100\n"
    config += "  ice: {}\n".format(True)
    config += "  ice_parameters:\n"
    config += "    a1: {}\n".format(0.72)
    config += "    a2: {}\n".format(0.28)
    config += "    density: {}\n".format(density)
    config += "    m1: {}\n".format(0)
    config += "    m2: {}\n".format(1/2.88)
    config += "    s1: {}\n".format(0.1)
    config += "    s2: {}\n".format(0.5)


    config += "  inelastic_model: {}\n".format(
        ['null', 'zero_loss', 'mp_loss', 'unfiltered', 'cc_corrected'][0])
    config += "  margin: {}\n".format(0)
    config += "  mp_loss_position: {}\n".format(['peak', 'optimal'][0])
    config += "  mp_loss_width: {}\n".format(20)
    config += "  padding: {}\n".format(100)
    config += "  radiation_damage_model: {}\n".format(True)
    config += "  sensitivity_coefficient: {}\n".format(0.08)
    config += "  slice_thickness: {}\n".format(3)

    with open(output_config, mode='w') as f:
        f.write(config)
